'use server'
import Image from 'next/image'
import { cache } from 'react'
import { createClient } from '../prismicio'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'
import Services from '../components/Services'
import '../styles/index.scss'

function getSliceByName(data, name) {

  return data.filter(item => {
    return item.slice_type == name
  });
}



export const getData = cache(async (id) => {
  const client = createClient()
  const page = await client.getSingle("homepage");

  return page.data.slices
})


export default async function Home() {

  const page = await getData()
  console.log(getSliceByName(page, 'contacts')[0]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Hero data={getSliceByName(page, 'hero')[0]} />
        <About data={getSliceByName(page, 'about')[0]} />
        <Services data={getSliceByName(page, 'service')} />
        <Contact data={getSliceByName(page, 'contacts')[0]} />
      </main>
    </>
  )
}