import Image from 'next/image'
import { cache } from 'react'
import { createClient } from '../prismicio'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'
import Services from '../components/Services'
import '../styles/index.scss'
import { SliceZone } from '@prismicio/react'
import { components } from '@/slices'
import ArrowUp from '@/components/ArrowUp'



function getSliceByName(data, name) {

  return data.filter(item => {
    return item.slice_type == name
  })[0]
}

export default async function Home() {

  const client = createClient()
  const page = await client.getSingle("homepage");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Hero data={getSliceByName(page.data.slices, 'hero')} />
        <About data={getSliceByName(page.data.slices, 'about')} />
        <Services data={getSliceByName(page.data.slices, 'service')} />
        <Contact data={getSliceByName(page.data.slices, 'contacts')} />
        <ArrowUp />
      </main>
    </>
  )
}

export async function generateMetadata() {
  const client = createClient();
  const page = await client.getSingle("homepage");

  return {
    title: page.data.meta_title,
    description: page.data.meta_description,
  };
}