// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contacts: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  service: dynamic(() => import("./Service")),
};
