// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  About: dynamic(() => import("./About")),
  Hero: dynamic(() => import("./Hero")),
};
